### ISSUE TITLE
Proposal to handle nil and other non-numeric values for binary ops ala floats and sNaNs

### ISSUE THREAD

**Issue by starbelly** [ericmj/decimal#122]
I think it would be beneficial for most if not all binary ops to raise or return a specific error message in the case of non-numeric values. This would be similar to what we do for sNaNs and floats. 

The current behavior:

```
iex(1)> Decimal.add(nil, 1)
** (FunctionClauseError) no function clause matching in Decimal.decimal/1

    The following arguments were given to Decimal.decimal/1:

        # 1
        nil

    Attempted function clauses (showing 4 out of 4):

        defp decimal(%Decimal{} = num)
        defp decimal(num) when is_integer(num)
        defp decimal(num) when is_binary(num)
        defp decimal(other) when is_float(other)

    (decimal) lib/decimal.ex:1902: Decimal.decimal/1
    (decimal) lib/decimal.ex:333: Decimal.add/2
iex(1)> Decimal.mult(1, nil)
** (FunctionClauseError) no function clause matching in Decimal.decimal/1

    The following arguments were given to Decimal.decimal/1:

        # 1
        nil

    Attempted function clauses (showing 4 out of 4):

        defp decimal(%Decimal{} = num)
        defp decimal(num) when is_integer(num)
        defp decimal(num) when is_binary(num)
        defp decimal(other) when is_float(other)

    (decimal) lib/decimal.ex:1902: Decimal.decimal/1
    (decimal) lib/decimal.ex:1028: Decimal.mult/2
```

The proposed behavior:
```
iex(1)> Decimal.mult(1, nil)
** (Decimal.Error) : operation on non-numeric value nil
iex(2)> Decimal.mult(1, :an_atom)
** (Decimal.Error) : operation on non-numeric value :an_atom
```

If agreed I will do a PR.

**Comment by ericmj** [comment]
Sounds good, but we should raise ArgumentError, like we do for floats.
